name: Deploy React to EC2

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -t voicevocab .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker tag voicevocab ${{ secrets.DOCKER_USERNAME }}/voicevocab:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/voicevocab:latest

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/voicevocab:latest
          docker stop voicevocab || true
          docker rm voicevocab || true
          docker run -d -p 80:80 -p 443:443 --name voicevocab \
          -e VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
          -v /home/${{ secrets.EC2_USER }}/voicevocab.store:/etc/voicevocab \
          ${{ secrets.DOCKER_USERNAME }}/voicevocab:latest
