name: Deploy React to EC2

on:
  push:
    branches: [ "main", "fix/dockerfile" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Build Docker image
      run: |
        docker build --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} -t voicevocab .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker tag voicevocab ${{ secrets.DOCKER_USERNAME }}/voicevocab:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/voicevocab:${{ github.sha }}

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/voicevocab:${{ github.sha }}
          docker stop voicevocab || true
          docker rm voicevocab || true
          docker run -d -p 80:80 -p 443:443 --name voicevocab \
          -e VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
          -v /home/${{ secrets.EC2_USER }}/voicevocab.store:/etc/voicevocab \
          ${{ secrets.DOCKER_USERNAME }}/voicevocab:${{ github.sha }}
