name: React build and deploy

on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache node modules 
        uses: actions/cache@v2
        with:
          path: node_modules 
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies 
        run: npm install 

      - name: Build 
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        run: npm run build 

      - name: Verify build output
        run: ls -la dist

      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp dist s3://action-practice-bapull --recursive --region ap-northeast-2
          # S3 웹사이트 설정을 위한 명령 (필요시)
          # aws s3 website s3://action-practice-bapull --index-document index.html --error-document index.html
          # Optionally invalidate CloudFront cache
          aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_ID --paths "/*"
